<?php

require_once "db_connection.php";

// Allow from any origin
if (isset($_SERVER['HTTP_ORIGIN'])) {
    header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
    header('Access-Control-Allow-Credentials: true');
    header('Access-Control-Max-Age: 86400');    // cache for 1 day
}

// Access-Control headers are received during OPTIONS requests
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PATCH, DELETE");

    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
        header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

    exit(0);
}

//todo: change all the sql queries, use prepared statements instead of escaping quotes using str_replace()

if ($_SERVER["REQUEST_METHOD"] === "PATCH") {
    $data = file_get_contents('php://input');

    $_PATCH = json_decode($data, true);

    if (isset($_PATCH["blocks"])) {

        $blocks = json_encode($_PATCH["blocks"]);
        $noteID = $_PATCH["noteID"];
        unset($_PATCH["noteID"]);

        // escape the double quotes that are generated by the plugins to add style to the text. They conflict with the double quotes used for JSON.
        foreach ($_PATCH["blocks"] as $key => $value) {

            $_PATCH["blocks"][$key]["data"]["text"] = str_replace("\\'", "''", addslashes($value["data"]["text"]));

        }
        echo var_dump($_PATCH);

        $_PATCH = json_encode($_PATCH);


        mysqli_query($conn, "UPDATE notes SET content='$_PATCH' WHERE noteID='$noteID'");

    } elseif (isset($_PATCH["title"])) {

        $title = str_replace("'", "''", $_PATCH["title"]);
        $noteID = $_PATCH["noteID"];
        mysqli_query($conn, "UPDATE notes SET title='$title' WHERE noteID='$noteID'");


    } else if (isset($_PATCH["name"], $_PATCH["color"], $_PATCH["folderID"])) {

        $folderName = str_replace("'", "''", $_PATCH["name"]);
        $folderColor = str_replace("'", "''", $_PATCH["color"]);
        $folderID = $_PATCH["folderID"];


        mysqli_query($conn, "UPDATE folders SET folderName='$folderName', color='$folderColor' WHERE folderID='$folderID'");

    }

}